linters:
  enable-all: true
  disable:
    - cyclop
    - funlen
    - gocyclo
    - godox
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - lll
    - nosnakecase
    - paralleltest
    - testpackage
    - varnamelen
    - wsl