package muse

const C = NoteName("C")
const CSHARP = NoteName("C#")
const D = NoteName("D")
const DSHARP = NoteName("D#")
const DFLAT = NoteName("Db")
const E = NoteName("E")
const EFLAT = NoteName("Eb")
const F = NoteName("F")
const FSHARP = NoteName("F#")
const G = NoteName("G")
const GSHARP = NoteName("G#")
const GFLAT = NoteName("Gb")
const A = NoteName("A")
const ASHARP = NoteName("A#")
const AFLAT = NoteName("Ab")
const B = NoteName("B")
const BFLAT = NoteName("Bb")
