package muse

const (
	C      = NoteName("C")
	DFLAT  = NoteName("Db")
	CSHARP = NoteName("C#")
	D      = NoteName("D")
	EFLAT  = NoteName("Eb")
	DSHARP = NoteName("D#")
	E      = NoteName("E")
	F      = NoteName("F")
	GFLAT  = NoteName("Gb")
	FSHARP = NoteName("F#")
	G      = NoteName("G")
	AFLAT  = NoteName("Ab")
	GSHARP = NoteName("G#")
	A      = NoteName("A")
	BFLAT  = NoteName("Bb")
	ASHARP = NoteName("A#")
	B      = NoteName("B")
)
