name: push
run-name: ${{ github.actor }} push GitHub Actions
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./... 

      - name: Test
        run: go test -v ./...

  codecov:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Run coverage
        run: go test ./... -coverprofile=coverage.out
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}